### ISSUE TITLE
Bookies at 100% CPU

### ISSUE THREAD

**Issue by sschepens** [apache/incubator-pulsar#1737]
We're experiencing apparently the same issue that we reported at #110
We having most of our bookies hang at 100% CPU while reading from rocksdb, but our disk metrics show little to no reads on the disks which is strange.

We're running pulsar 1.20 and bookkeeper version 4.3.1.72-yahoo.

Here is a jstack from a bookie:

[jstack.txt](https://github.com/apache/incubator-pulsar/files/1977178/jstack.txt)

Our bookkeeper config is the following:

[bk.conf.txt](https://github.com/apache/incubator-pulsar/files/1977179/bk.conf.txt)

This is currently affecting one of our production clusters and don't really know how to mitigate it.

@merlimat @sijie do any of you know how to mitigate or fix this, this is of course an issue with the rocksdb storage of bookkeeper.

I found [this](https://github.com/facebook/rocksdb/issues/261) issue on rocksdb which talks about poor iterato4 performance when iterating through lots of tombstoned items, seems like this could be the case, or at least it expresses the same simptoms. We tried rebuilding the rocksdb index iusing bookkeeper cli and that seemed to work ok, maybe because that rebuilding made a clean index without tombstones?

Do you think this is the case? How could we mitigate this? In the issue they talk about caching the element just after the last deleted.

**Comment by merlimat** [comment]
@sschepens I think to remember that there was some fix between Rocksdb-5.5.5 and 5.8 to handle these cases, though I haven't found the PR/commit yet. 

> I found this issue on rocksdb which talks about poor iterato4 performance when iterating through lots of tombstoned items, seems like this could be the case, or at least it expresses the same simptoms. 

There shouldn't be many tombstones in this case, since we're doing a `DeleteRange()` from (ledgerid, 0) to (ledgerId+1, 0). The delete range drops the range in a single shot, but it has additional logic and in rocksdb-5.5 there were some of these issues.

I would suggest to either upgrade bookies, or at least upgrade the `rocksdbjni.jar` to 5.8.6 or newer.

> We tried rebuilding the rocksdb index iusing bookkeeper cli and that seemed to work ok, maybe because that rebuilding made a clean index without tombstones?

Correct, rebuilding the index scans the entry logs and reconstruct a new index from scratch, so it would not have the baggage of the old index.

**Comment by sschepens** [comment]
@merlimat I would like to upgrade bookkeeper straight to official Apache 4.7, are these versions compatible with the Yahoo version of bookkeeper and with pulsar 1.20?

**Comment by merlimat** [comment]
Yes @sschepens , the bookies on 4.7 are perfectly compatible with the bookkeper client from yahoo branch, which based on 4.3 release. Some care would only be required if authentication (broker->bookie) was enabled, but I don't think that's relevant for anyone except Yahoo (since there are not even auth plugin implementation available fro 4.3 in OSS).

**Comment by bardock** [comment]
@merlimat, We saw that the size of the folder `/data/ledgers/current/locations` was 25 GB before and 3 GB after rebuilding the index. Do you know if there is any setting that could prevent this growing? Or updating bookies and rocksdb is the only fix?

Beyond that, do you think that 3 GB for a clean index is ok? Our bookies currently have 4 GB for blockCacheSize.

Thanks!

**Comment by sschepens** [comment]
@merlimat could you help us with this please?
We're seeing the the locations folder tends to grow a lot and after rebuilding the index, the size drops a lot. Could it be that rocksdb is not deleting the data? Or that it's not compacting frequently?

Is there any settings to tweak this?

**Comment by sijie** [comment]
I think the 100% cpu usage is related to deleteRange. the change is merged to bk 4.7.2 and will be included in pulsar 2.1.1 and 2.2.0 releases.
