### ISSUE TITLE
TLS auth cannot be used between proxy and brokers

### ISSUE THREAD

**Issue by ivankelly** [apache/incubator-pulsar#1991]
Brokers are configured to use TLS authentication

Proxies cannot connect to the TLS authentication required brokers, because the brokers are advertising their address as :8080, not :8443

**Comment by ivankelly** [comment]
My original hunch on the advertising being wrong was incorrect. It does in fact go to the correct address if you have the right set of options configured.

my proxy.conf tls bits
```
authenticationEnabled=true
authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderTls
authorizationEnabled=true
brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationTls
brokerClientAuthenticationParameters=tlsCertFile:/home/ivan/src/pulsar/checkouts/testing-ca/tests/certificate-authority/client-keys/admin.cert.pem,tlsKeyFile:/home/ivan/src/pulsar/checkouts/testing-ca/tests/certificate-authority/client-keys/admin.key-pk8.pem
brokerClientTrustCertsFilePath=/home/ivan/src/pulsar/checkouts/testing-ca/tests/certificate-authority/certs/ca.cert.pem                                                                                                               
tlsEnabledInProxy=true
tlsEnabledWithBroker=true
tlsCertificateFilePath=/home/ivan/src/pulsar/checkouts/testing-ca/tests/certificate-authority/server-keys/broker.cert.pem
tlsKeyFilePath=/home/ivan/src/pulsar/checkouts/testing-ca/tests/certificate-authority/server-keys/broker.key-pk8.pem
tlsTrustCertsFilePath=/home/ivan/src/pulsar/checkouts/testing-ca/tests/certificate-authority/certs/ca.cert.pem
tlsAllowInsecureConnection=true
```

my broker.conf tls bits
```
tlsEnabled=true
tlsCertificateFilePath=/pulsar/ssl/broker.cert.pem
tlsKeyFilePath=/pulsar/ssl/broker.key-pk8.pem
tlsTrustCertsFilePath=/pulsar/ssl/ca.cert.pem
authenticationEnabled=true
authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderTls
superUserRoles=admin
authorizationEnabled=true
```

tlsAllowInsecureConnection doesn't exist in the config file as is. It needs to be documented.

This works for the brokerService port. I have another role "ivan".
If "ivan" tries to produce to public/default/topic1 via the proxy or broker, he cannot. If the admin user grants "ivan" produce action permissions on the public/default namespace, then he can write.

However, if "ivan" uses they admin client against the proxy, he can grant himself any permissions he wants.

This is because the proxy is authenticated against the broker as a superuser, anyone authenticated against the proxy gains those superuser powers. There's no forwarding of principal from the proxy for admin like there is for data.

**Comment by pckeyan** [comment]
@ivankelly @sijie Is this not an issue? Is this tested in K8s along with nodeport config?

**Comment by ivankelly** [comment]
@pckeyan This is an issue, yes. Working on a fix now, though I'm testing directly in docker locally. Will add a task for testing with nodeport in k8s also.

**Comment by ivankelly** [comment]
@jai1 @merlimat I've been looking at how proxyRoles and originalPrincipal work with the data protocol. Is it correct to say that, with this mechanism, you need to explicitly grant produce and consume to the proxy role on every individual namespace that you want accessible through the proxy?

**Comment by pckeyan** [comment]
@ivankelly I tested with the identified parameter, SSL is working is fine between Proxy and Broker in K8s. Thanks for your help. Appreciated.

**Comment by ivankelly** [comment]
@pckeyan do you have authorization enabled? The problem with the parameters I put is that any client that is authorized with the proxy will have full superuser access for admin operations, which obviously isn't ideal.

**Comment by pckeyan** [comment]
Yes I have authorization enabled, I tested across LOBs of my use case and is rightly declined. Let me retest. Let me know if you want me to test some thing different. I have card and bank as two lobs. Card owned topic cannot be used by bank to produce/consume.

**Comment by ivankelly** [comment]
produce/consume isn't the problem. The problem is that someone authorized as bank can use the admin api to grant permissions to themselves to produce/consume on a card owned topic.

**Comment by pckeyan** [comment]
But still they need Certificates to pass it on to get authenticated; Please correct my understanding

**Comment by ivankelly** [comment]
@pckeyan yes, it's not wide open, but it's more open than it should be.

**Comment by pckeyan** [comment]
@ivankelly Are you planning for a fix there? What would be ideal fix?

**Comment by ivankelly** [comment]
@pckeyan I'd like to talk to @merlimat & @jai1 since they've worked on similar stuff, but the planned fix is to send the original authenticated rolename with the proxied requests, similiar to how we do for the data protocol. Then we'd need to document all this stuff, because there's no documentation right now. Hopefully I can knock out the fix tomorrow.

**Comment by jai1** [comment]
Hi Ivan,

Since proxy was meant to be on a public IP we have added extra
authentication checks to prevent MITM attacks and safeguard against
compromised proxies. - but all these extra checks are configurable and are
turned off by default.

a. You can set disable authentication and authorization and proxy to
disable all checks. (Not recommended for production)

b. If authentication and authorization is enabled on Proxy and Broker, and
if a consume or produce action is via a proxy the
    - originalPrincipal - will contain Client role name  (aka principal)
    - authRole - will contain Proxy role name, extracted from
authenticationData and authMethod sent by the proxy
    - Both the Proxy and the end Client *should* have the appropriate
consume or produce permissions or else a compromised proxy can mimic any
client by just sending a stolen originalPrincipal (string). Or in other
words a compromised proxy should not be able to access more data than a
compromised client.

b. OriginalPrincipal is just a string and can easily be remanufactured by a
compromised proxy, so in order to safeguard the service you can enable  "
*forwardAuthorizationCredentials*" on the proxy and enable "
*authenticateOriginalAuthData*" on the broker.
    - The proxy will forward the client authenticationData (digital
signature with TTL) and authenticationData instead of a string and the
broker will authenticate the end client and extract originalPrincipal from
client authenticationData.

c. Another scenario could be that the proxy mimics the client by setting
originalPrincipal as NULL
   - In order to prevent that you can set "*proxyRoles*" in the broker
configuration.


Below are some links to the configurations you can set. This weekend I will
go through the documentation and add any missing pieces (if any).

https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L247
https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L251
https://github.com/apache/incubator-pulsar/blob/master/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java#L79

Regards,
Jai

**Comment by ivankelly** [comment]
> " *forwardAuthorizationCredentials*" on the proxy and enable " *authenticateOriginalAuthData*"

I assume this only applies to Athenz, as TLS doesn't use the auth data AFAICS.

> This weekend I will go through the documentation and add any missing pieces (if any)

There's quite a bit missing, in particular for the TLS auth context, which most people will be using. Once I've solved this issue, I'll take a pass over the docs too. 

In terms of this issue, my plan is to make the admin api respect originalPrincipal and proxyRoles also, carrying it in a header ("X-Original-Principal"). 

This does mean that proxy would have to be added as admin role for each tenant that wants to use admin api through the proxy. In some usecases though, I think proxy will have to be a superuser at the proxy.

**Comment by sijie** [comment]
This has been fixed by multiple pull requests linked above.
