### ISSUE TITLE
Use pulsar-daemon start zookeeper will use port of 8080

### ISSUE THREAD

**Issue by codelipenghui** [apache/incubator-pulsar#2324]
Happens in version 2.1.0-incubating

```shell
$ bin/pulsar-daemon start zookeeper
```
I see that port of 8080 be used.

**Comment by sijie** [comment]
@codelipenghui : 

in zookeeper 3.5, zookeeper will start an admin server at 8080. that's why the port of 8080 is used.
what you can do is adding following settings to the zookeeper configuration file. you can either disable zookeeper admin server, or changing the admin server port to a different port (e.g. 9990).

```
admin.enableServer=true
admin.serverPort=9990
```

I have a pull request #2331 on adding them to configuration files.

**Comment by sijie** [comment]
Close this one since it was answered.
