### ISSUE TITLE
Looks like a small user base on SO. Marketing efforts? Will the project last?

### ISSUE THREAD

**Issue by RobIsHere** [apache/incubator-pulsar#2462]
I'm looking into Pulsar and from an architectural standpoint it's made like I would have designed the system. So I'd prefer it over Kafka from this perspective. But there is a really small user base, e.g. only some messages about Pulsar on Stackoverflow.

So my quesition is: as there are many technical better projects loosing against others that are better in marketing - will this project last and what do you do to get users onboard? 

I think this is a quesition that concerns a lot of people who look on pulsar. Because even when pulsar is open source, my Investment in my software that works with pulsar is huge. Addressing this on the web or in docs could make sense.

**Comment by jonb-streamlio** [comment]
@RobIsHere appreciate the question. Although the software has been in production use at Yahoo for over 3 years, it was only open sourced as Apache Pulsar more recently and so is still earlier in its lifecycle than some other projects.

That said, there is a rapidly growing number of Pulsar users. A number of them are big companies who like its performance and scalability (but who don't like to talk publicly about newer parts of their technology stack), and there are also a growing number of mid-size and even startup companies using it for its flexibility and features. For example there's a large industrial company using it, a well-known consumer electronics company, a large media company, a transportation services startup, and a tax planning company, just to name a few.  (For what it's worth, StackOverflow isn't always an accurate indicator of adoption--I've worked for companies who had several hundred companies using the technology but very little activity on StackOverflow. When there are responsive, knowledgeable alternatives such as a vendor supporting the technology, questions tend to go directly there instead.)

It's true that the connector ecosystem is smaller than that of longer-established projects like Kafka, but with the recent release of Pulsar IO (see https://streaml.io/blog/introducing-pulsar-io/), it's become a lot easier for new connectors to be created. At Streamlio we've been working with a number of customers and solutions partners on connectors using that framework, which will also help expand the connector universe. In addition the client options continue to grow--in addition to C++, Java, and Python, there have been recent new additions from the Pulsar community including Go (see https://pulsar.apache.org/docs/en/client-libraries/#go-client and https://github.com/Comcast/pulsar-client-go) and Scala (https://github.com/sksamuel/pulsar4s).

To the broader question of whether marketing is the deciding factor in success of new projects, in general marketing isn't the biggest factor in the early days of a project, it's the technology-savvy people who look beyond "what is a safe choice because lots of other people are doing it" to adopt new technology based on understanding the differentiation in the technology and connecting that to what matters for them. With that as the foundation, marketing ramps up and helps to scale sharing their stories to the broader set of adopters who are less driven by an understanding of the technology differentiation and more by seeing that other people like them are using it.

The great thing about newer projects is how quickly they evolve--without the legacy baggage of design decisions made years ago, they generally outpace older technologies in innovation, which adds fuel to the early adoption fires.

**Comment by joefk** [comment]
Yahoo/Oath is running Pulsar is production  at a large scale;  and will continue to do so.

**Comment by pckeyan** [comment]
This is a great question with a vision to decide future of a product. Let me fill in my thoughts. 
As a user:
I was looking for a very good alternative for Kafka based upon its disadvantages. I am a techie looking for a better product looked into many products available in OpenSource world - ended up with Pulsar based upon its architecture and cloud adoption flexibility. Future lies on how it adopts to changing strategies in software world - Cloud. It is easy for me to launch Pulsar in Bare Metal in Cloud or on a Kubernetes Cluster or on a GKE or AKS etc. Features that are inflight will make Pulsar more robust. I believe Pulsar will make it BIG based on its Architecture and easy to launch.
Regarding SO, I would say the visit is declining phase as many projects are available on IM. Considering my example, I am working on Jpos, Pulsar, reactor-core and Spring. They are available on Slack and Gitter respectively. I felt it is easy to connect like FTF with the leads and community. We can ping directly/work directly in case to solve a issue then and there. I felt this model is more productive. You can join the channel anytime and can search to find whether those questions are answered before like SO. My 2 cents.

**Comment by RobIsHere** [comment]
The fact that there is a growing number of mid-size companies and also a CE company from outside of the tech-bubble is very positive. It's good to see that you have a wider focus and they appreciate your work. I'm going to use pulsar.

**Comment by ivankelly** [comment]
It looks like this question has been resolved, so closing the issue.
